# Generated by Django 5.2.2 on 2025-06-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_email_publicly',
            field=models.BooleanField(default=False),
        ),
    ]
